CC = g++
CFLAGS = -Wall -std=c++11

all: main

main: main.o OptionPricing.o
	$(CC) $(CFLAGS) main.o OptionPricing.o -o main

main.o: main.cpp OptionPricing.h
	$(CC) $(CFLAGS) -c main.cpp

OptionPricing.o: OptionPricing.cpp OptionPricing.h
	$(CC) $(CFLAGS) -c OptionPricing.cpp

clean:
	rm -f main.o OptionPricing.o main